apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: srpingboot
        image: 039088331584.dkr.ecr.ap-northeast-2.amazonaws.com/guestbook:1.0
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_IP
          value: "3.35.252.94"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: "guestbook"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "edu"
        resources:
          requests:
             cpu: 250m
